In [2]:
from sklearn  import datasets

In [3]:
from pandas import DataFrame

In [17]:
import pandas as pd

In [7]:
x_data=datasets.load_iris().data#返回iris数据集所有输入特征

In [25]:
y_data=datasets.load_iris().target#返回iris数据集所有标签
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
print("x_data from datasets: \n",x_data)

x_data from datasets: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3

In [14]:
print("y_data from datasets: \n",y_data)

y_data from datasets: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


为表格增加行索引（左侧）和列标签（上方）

In [26]:
x_data=DataFrame(x_data,columns=['花萼长度','花萼宽度','花瓣长度','花瓣宽度'])

In [29]:
pd.set_option('display.unicode.east_asian_width',True)#设置列名对齐

In [30]:
x_data

花萼长度  花萼宽度  花瓣长度  花瓣宽度
0         5.1       3.5       1.4       0.2
1         4.9       3.0       1.4       0.2
2         4.7       3.2       1.3       0.2
3         4.6       3.1       1.5       0.2
4         5.0       3.6       1.4       0.2
..        ...       ...       ...       ...
145       6.7       3.0       5.2       2.3
146       6.3       2.5       5.0       1.9
147       6.5       3.0       5.2       2.0
148       6.2       3.4       5.4       2.3
149       5.9       3.0       5.1       1.8

[150 rows x 4 columns]

In [32]:
x_data['类别']=y_data#新加一列，列名为“类别”,数据为y_data
x_data

花萼长度  花萼宽度  花瓣长度  花瓣宽度  类别
0         5.1       3.5       1.4       0.2     0
1         4.9       3.0       1.4       0.2     0
2         4.7       3.2       1.3       0.2     0
3         4.6       3.1       1.5       0.2     0
4         5.0       3.6       1.4       0.2     0
..        ...       ...       ...       ...   ...
145       6.7       3.0       5.2       2.3     2
146       6.3       2.5       5.0       1.9     2
147       6.5       3.0       5.2       2.0     2
148       6.2       3.4       5.4       2.3     2
149       5.9       3.0       5.1       1.8     2

[150 rows x 5 columns]

In [33]:
irisDataFrame=pd.DataFrame(data=x_data)
irisDataFrame

花萼长度  花萼宽度  花瓣长度  花瓣宽度  类别
0         5.1       3.5       1.4       0.2     0
1         4.9       3.0       1.4       0.2     0
2         4.7       3.2       1.3       0.2     0
3         4.6       3.1       1.5       0.2     0
4         5.0       3.6       1.4       0.2     0
..        ...       ...       ...       ...   ...
145       6.7       3.0       5.2       2.3     2
146       6.3       2.5       5.0       1.9     2
147       6.5       3.0       5.2       2.0     2
148       6.2       3.4       5.4       2.3     2
149       5.9       3.0       5.1       1.8     2

[150 rows x 5 columns]

In [22]:
csvPath='iris.csv'

In [23]:
irisDataFrame.to_csv(csvPath,header=True,encoding="gbk")

训练模型

In [34]:
import tensorflow as tf

2022-04-26 15:41:37.651567: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [35]:
import numpy as np

In [36]:
from matplotlib import pyplot as plt

In [37]:
x_train=datasets.load_iris().data
y_train=datasets.load_iris().target

In [38]:
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [39]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
np.random.seed(116)

In [41]:
np.random.shuffle(x_train)

In [42]:
np.random.seed(116)

In [43]:
np.random.shuffle(y_train)

In [44]:
tf.random.set_seed(116)

神经网络搭建

In [46]:
model=tf.keras.models.Sequential([tf.keras.layers.Dense(3,activation=tf.nn.softmax,kernel_regularizer=tf.keras.regularizers.l2())])

2022-04-26 15:48:49.376508: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-04-26 15:48:49.380188: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-04-26 15:48:50.077083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-26 15:48:50.077457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce MX450 computeCapability: 7.5
coreClock: 1.44GHz coreCount: 14 deviceMemorySize: 1.83GiB deviceMemoryBandwidth: 52.17GiB/s
2022-04-26 15:48:50.077510: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-04-26 15:48:50.096569: I tensorflow/stream_executor/platform/default

In [47]:
model.compile(
optimizer=tf.keras.optimizers.SGD(lr=0.1),
loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
metrics=tf.keras.metrics.sparse_categorical_accuracy)

In [48]:
model.fit(x_train,y_train,batch_size=32,epochs=500,validation_split=0.2,validation_freq=20)
model.compile()

2022-04-26 15:52:11.813955: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-04-26 15:52:11.835971: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2419200000 Hz
2022-04-26 15:52:12.003033: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10


Epoch 1/500
4/4 [==============================] - 0s 2ms/step - loss: 2.8038 - sparse_categorical_accuracy: 0.3533
Epoch 2/500
4/4 [==============================] - 0s 1ms/step - loss: 1.0218 - sparse_categorical_accuracy: 0.6467
Epoch 3/500
4/4 [==============================] - 0s 921us/step - loss: 0.9625 - sparse_categorical_accuracy: 0.6250
Epoch 4/500
4/4 [==============================] - 0s 1ms/step - loss: 0.6996 - sparse_categorical_accuracy: 0.6875
Epoch 5/500
4/4 [==============================] - 0s 916us/step - loss: 1.0346 - sparse_categorical_accuracy: 0.6067
Epoch 6/500
4/4 [==============================] - 0s 999us/step - loss: 0.7820 - sparse_categorical_accuracy: 0.6165
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6032 - sparse_categorical_accuracy: 0.7129
Epoch 8/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5836 - sparse_categorical_accuracy: 0.7369
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - l

4/4 [==============================] - 0s 1ms/step - loss: 0.4384 - sparse_categorical_accuracy: 0.8683
Epoch 70/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3658 - sparse_categorical_accuracy: 0.9327
Epoch 71/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4900 - sparse_categorical_accuracy: 0.7852
Epoch 72/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3962 - sparse_categorical_accuracy: 0.9231
Epoch 73/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5942 - sparse_categorical_accuracy: 0.7694
Epoch 74/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3902 - sparse_categorical_accuracy: 0.9006
Epoch 75/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3800 - sparse_categorical_accuracy: 0.9392
Epoch 76/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3875 - sparse_categorical_accuracy: 0.9367
Epoch 77/500
4/4 [==============================] - 0s 998us/step - loss: 0.4

4/4 [==============================] - 0s 1ms/step - loss: 0.4194 - sparse_categorical_accuracy: 0.8842
Epoch 138/500
4/4 [==============================] - 0s 983us/step - loss: 0.3652 - sparse_categorical_accuracy: 0.9500
Epoch 139/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3830 - sparse_categorical_accuracy: 0.9381
Epoch 140/500
4/4 [==============================] - 0s 9ms/step - loss: 0.5252 - sparse_categorical_accuracy: 0.7798 - val_loss: 0.3758 - val_sparse_categorical_accuracy: 1.0000
Epoch 141/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3801 - sparse_categorical_accuracy: 0.9383
Epoch 142/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3750 - sparse_categorical_accuracy: 0.9573
Epoch 143/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3403 - sparse_categorical_accuracy: 0.9392
Epoch 144/500
4/4 [==============================] - 0s 954us/step - loss: 0.3400 - sparse_categorical_accuracy: 0.9565
Epoch

4/4 [==============================] - 0s 1ms/step - loss: 0.3612 - sparse_categorical_accuracy: 0.9681
Epoch 205/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3551 - sparse_categorical_accuracy: 0.9319
Epoch 206/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4474 - sparse_categorical_accuracy: 0.8200
Epoch 207/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5569 - sparse_categorical_accuracy: 0.7485
Epoch 208/500
4/4 [==============================] - 0s 983us/step - loss: 0.3941 - sparse_categorical_accuracy: 0.9127
Epoch 209/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3806 - sparse_categorical_accuracy: 0.9260
Epoch 210/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3918 - sparse_categorical_accuracy: 0.9146
Epoch 211/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4518 - sparse_categorical_accuracy: 0.8102
Epoch 212/500
4/4 [==============================] - 0s 1ms/step - l

4/4 [==============================] - 0s 1ms/step - loss: 0.3718 - sparse_categorical_accuracy: 0.9308
Epoch 272/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3465 - sparse_categorical_accuracy: 0.9479
Epoch 273/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3886 - sparse_categorical_accuracy: 0.8815
Epoch 274/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3544 - sparse_categorical_accuracy: 0.9650
Epoch 275/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3611 - sparse_categorical_accuracy: 0.9108
Epoch 276/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3458 - sparse_categorical_accuracy: 0.9675
Epoch 277/500
4/4 [==============================] - 0s 979us/step - loss: 0.4461 - sparse_categorical_accuracy: 0.8471
Epoch 278/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3668 - sparse_categorical_accuracy: 0.9581
Epoch 279/500
4/4 [==============================] - 0s 1ms/step - l

4/4 [==============================] - 0s 1ms/step - loss: 0.4404 - sparse_categorical_accuracy: 0.8413
Epoch 339/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3382 - sparse_categorical_accuracy: 0.9529
Epoch 340/500
4/4 [==============================] - 0s 10ms/step - loss: 0.4161 - sparse_categorical_accuracy: 0.8663 - val_loss: 0.3289 - val_sparse_categorical_accuracy: 1.0000
Epoch 341/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3617 - sparse_categorical_accuracy: 0.9435
Epoch 342/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4020 - sparse_categorical_accuracy: 0.8908
Epoch 343/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4296 - sparse_categorical_accuracy: 0.8571
Epoch 344/500
4/4 [==============================] - 0s 900us/step - loss: 0.4544 - sparse_categorical_accuracy: 0.8363
Epoch 345/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3698 - sparse_categorical_accuracy: 0.9487
Epoch 

4/4 [==============================] - 0s 1ms/step - loss: 0.4113 - sparse_categorical_accuracy: 0.8758
Epoch 406/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3241 - sparse_categorical_accuracy: 0.9719
Epoch 407/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4788 - sparse_categorical_accuracy: 0.8248
Epoch 408/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3406 - sparse_categorical_accuracy: 0.9721
Epoch 409/500
4/4 [==============================] - 0s 976us/step - loss: 0.3561 - sparse_categorical_accuracy: 0.9244
Epoch 410/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3467 - sparse_categorical_accuracy: 0.9435
Epoch 411/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4042 - sparse_categorical_accuracy: 0.8527
Epoch 412/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3709 - sparse_categorical_accuracy: 0.9031
Epoch 413/500
4/4 [==============================] - 0s 1ms/step - l

4/4 [==============================] - 0s 2ms/step - loss: 0.4786 - sparse_categorical_accuracy: 0.8108
Epoch 473/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5449 - sparse_categorical_accuracy: 0.8565
Epoch 474/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5338 - sparse_categorical_accuracy: 0.7581
Epoch 475/500
4/4 [==============================] - 0s 3ms/step - loss: 0.3426 - sparse_categorical_accuracy: 0.9569
Epoch 476/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3244 - sparse_categorical_accuracy: 0.9573
Epoch 477/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3665 - sparse_categorical_accuracy: 0.9233
Epoch 478/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4405 - sparse_categorical_accuracy: 0.8417
Epoch 479/500
4/4 [==============================] - 0s 875us/step - loss: 0.4336 - sparse_categorical_accuracy: 0.8562
Epoch 480/500
4/4 [==============================] - 0s 10ms/step - 

In [49]:
model.save('saved_model/my_iris_model')

INFO:tensorflow:Assets written to: saved_model/my_iris_model/assets


2022-04-26 15:53:22.538685: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
